In [61]:
!pip install pandas
import pandas as pd

Requirement already satisfied: pandas in C:\Users\User\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (3.0.5)
Requirement already satisfied: numpy>=2.3.3 in C:\Users\User\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from pandas) (2.5.3)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\User\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in C:\Users\User\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from pandas) (2026.4)
Requirement already satisfied: six>=1.5 in C:\Users\User\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

[notice] A new release of pip is available: 26.1.2 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [62]:
path = r"CD2022_Populacao_2010_Compatibilizada_20231222.xlsx" 
bruto = pd.read_excel(path, header=None)

In [63]:
tabela = bruto.iloc[3:5573, 1:8].copy()

In [64]:
tabela.columns = ["uf","cod_uf","cod_munic","municipio","pop_2010_sinopse","pop_2010_compatibilizada","pop_2022"]

In [65]:
tabela = tabela.reset_index(drop=True)

In [66]:
tabela

,uf,cod_uf,cod_munic,municipio,pop_2010_sinopse,pop_2010_compatibilizada,pop_2022
0,RO,11,00015,Alta Floresta D'Oeste,24392,24392,21494
1,RO,11,00023,Ariquemes,90353,90353,96833
2,RO,11,00031,Cabixi,6313,6313,5351
3,RO,11,00049,Cacoal,78574,78574,86887
4,RO,11,00056,Cerejeiras,17029,17029,15890
...,...,...,...,...,...,...,...
5565,GO,52,22005,Vianópolis,12548,12548,14956
5566,GO,52,22054,Vicentinópolis,7371,7373,8768
5567,GO,52,22203,Vila Boa,4735,4735,4215
5568,GO,52,22302,Vila Propício,5145,5145,5815
5569,DF,53,00108,Brasília,2570160,2572159,2817381

In [67]:
for col in ["cod_uf","pop_2010_sinopse","pop_2010_compatibilizada","pop_2022"]: tabela[col] = pd.to_numeric(tabela[col], errors="coerce")

In [68]:
pop_por_estado = ( tabela.groupby("uf")[["pop_2010_compatibilizada", "pop_2022"]] .sum() .reset_index() )

In [69]:
pop_por_estado["diferenca"] = pop_por_estado["pop_2022"] - pop_por_estado["pop_2010_compatibilizada"]

In [70]:
pop_por_estado = pop_por_estado.sort_values("diferenca", ascending=False)

In [71]:
pop_por_estado.to_csv("populacao_por_estado.csv", sep=";", index=False)

In [72]:
pop_por_estado

    uf  pop_2010_compatibilizada  pop_2022  diferenca
25  SP                  41262199  44411238    3149039
23  SC                   6248436   7610361    1361925
8   GO                   6001789   7056495    1054706
17  PR                  10444526  11444380     999854
10  MG                  19597330  20539989     942659
12  MT                   3035122   3658649     623527
13  PA                   7581051   8120131     539080
2   AM                   3483985   3941613     457628
5   CE                   8451644   8794957     343313
7   ES                   3514952   3833712     318760
11  MS                   2449024   2757013     307989
15  PE                   8796055   9058931     262876
6   DF                   2572159   2817381     245222
14  PB                   3766528   3974687     208159
9   MA                   6574789   6776699     201910
22  RS                  10693929  10882965     189036
21  RR                    450479    636707     186228
16  PI                   3119097   3271199     152102
24  SE                   2067852   2210004     142152
19  RN                   3168027   3302729     134702
26  TO                   1383445   1511460     128015
4   BA                  14017071  14141626     124555
0   AC                    733559    830018      96459
18  RJ                  15989929  16055174      65245
3   AP                    669526    733759      64233
20  RO                   1562409   1581196      18787
1   AL                   3120887   3127683       6796

In [73]:
pop_por_municipio = tabela[
    ["uf", "cod_uf", "cod_munic", "municipio", "pop_2010_compatibilizada", "pop_2022"]
].copy()

pop_por_municipio

,uf,cod_uf,cod_munic,municipio,pop_2010_compatibilizada,pop_2022
0,RO,11,00015,Alta Floresta D'Oeste,24392,21494
1,RO,11,00023,Ariquemes,90353,96833
2,RO,11,00031,Cabixi,6313,5351
3,RO,11,00049,Cacoal,78574,86887
4,RO,11,00056,Cerejeiras,17029,15890
...,...,...,...,...,...,...
5565,GO,52,22005,Vianópolis,12548,14956
5566,GO,52,22054,Vicentinópolis,7373,8768
5567,GO,52,22203,Vila Boa,4735,4215
5568,GO,52,22302,Vila Propício,5145,5815
5569,DF,53,00108,Brasília,2572159,2817381

In [74]:
pop_por_municipio["diferenca"] = pop_por_municipio["pop_2022"] - pop_por_municipio["pop_2010_compatibilizada"]

In [75]:
pop_por_municipio = pop_por_municipio.sort_values("diferenca", ascending=False)

In [80]:
pop_por_municipio.to_csv("populacao_por_municipio.csv", sep=";", index=False)

In [81]:
pop_por_municipio

,uf,cod_uf,cod_munic,municipio,pop_2010_compatibilizada,pop_2022,diferenca
111,AM,13,02603,Manaus,1802014,2063689,261675
5569,DF,53,00108,Brasília,2572159,2817381,245222
3829,SP,35,50308,São Paulo,11253503,11451999,198496
3848,SP,35,52205,Sorocaba,586816,723682,136866
5417,GO,52,08707,Goiânia,1301912,1437366,135454
...,...,...,...,...,...,...,...
4931,RS,43,14902,Porto Alegre,1409351,1332845,-76506
169,PA,15,01402,Belém,1393399,1303403,-89996
3247,RJ,33,04904,São Gonçalo,999728,896744,-102984
3242,RJ,33,04557,Rio de Janeiro,6320446,6211223,-109223
2162,BA,29,27408,Salvador,2675656,2417678,-257978